# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lossR <- function(xy, iRow, radius, ED, ThreeD) {
    .Call('vennplot_loss_R', PACKAGE = 'vennplot', xy, iRow, radius, ED, ThreeD)
}

LossR <- function(xy, radius, ED, ThreeD) {
    .Call('vennplot_Loss_R', PACKAGE = 'vennplot', xy, radius, ED, ThreeD)
}

LoopR <- function(xy, ALPHA, radius, ED, ThreeD) {
    .Call('vennplot_loop_R', PACKAGE = 'vennplot', xy, ALPHA, radius, ED, ThreeD)
}

transR <- function(xy, radius, radiusvec, radiusall) {
    .Call('vennplot_trans_R', PACKAGE = 'vennplot', xy, radius, radiusvec, radiusall)
}

alldisR <- function(xy1, xy2, radius1, radius2, delta) {
    .Call('vennplot_alldis_R', PACKAGE = 'vennplot', xy1, xy2, radius1, radius2, delta)
}

closeR <- function(xy1, xy2, radius1, radius2, delta, direc) {
    .Call('vennplot_close_R', PACKAGE = 'vennplot', xy1, xy2, radius1, radius2, delta, direc)
}

listR1 <- function(M, xy, radius, k, yuan, xuan, num) {
    .Call('vennplot_list_R1', PACKAGE = 'vennplot', M, xy, radius, k, yuan, xuan, num)
}

listR2 <- function(myList, m, num) {
    .Call('vennplot_list_R2', PACKAGE = 'vennplot', myList, m, num)
}

listR3 <- function(M, Me) {
    .Call('vennplot_list_R3', PACKAGE = 'vennplot', M, Me)
}

listR4 <- function(M) {
    .Call('vennplot_list_R4', PACKAGE = 'vennplot', M)
}

